const menu_data = [
  {
    id: 1,
    mega_menu: false,
    has_dropdown: false,
    title: "Home",
    link: "/",
    active: "active",
    sub_menus: [{ link: "/", title: "Home" }],
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: false,
    title: "About",
    link: "/about",
    active: "active",
    sub_menus: [{ link: "/about", title: "About" }],
  },
  {
    id: 3,
    mega_menu: false,
    has_dropdown: false,
    title: "Contact",
    link: "/contact",
    active: "active",
    sub_menus: [{ link: "/contact", title: "Contact" }],
  },
  // {
  //   id: 3,
  //   mega_menu: false,
  //   has_dropdown: true,
  //   title: "Service",
  //   link: "/service",
  //   active: "",
  //   sub_menus: [
  //     { link: "/service", title: "Service 1" },
  //     { link: "/service-2", title: "Service 2" },
  //     { link: "/service-3", title: "Service 3" },
  //     { link: "/service-details", title: "Service Details" },
  //   ],
  // },
  // {
  //   id: 4,
  //   mega_menu: false,
  //   has_dropdown: false,
  //   title: "Research",
  //   link: "/research",
  //   active: "",
  // },
  // {
  //   id: 5,
  //   mega_menu: false,
  //   has_dropdown: true,
  //   title: "Blog",
  //   link: "/blog",
  //   active: "",
  //   sub_menus: [
  //     { link: "/blog", title: "Blog" },
  //     { link: "/blog-details", title: "Blog Details" },
  //   ],
  // },
  // {
  //   id: 6,
  //   mega_menu: false,
  //   has_dropdown: false,
  //   title: "Contact",
  //   link: "/contact",
  //   active: "",
  // },
];
export default menu_data;
